# Generated by Django 2.1.4 on 2020-10-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='author',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='author',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='author',
        ),
    ]
