# Generated by Django 3.0.7 on 2021-01-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegan', '0002_auto_20201022_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://www.france-hotel-guide.com/fr/blog/wp-content/uploads/SOL-SEMILLA.jpg?ezimgfmt=ng:webp/ngcb5'),
            preserve_default=False,
        ),
    ]
