# Generated by Django 3.0.7 on 2021-01-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegan', '0003_restaurant_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='picture',
            field=models.ImageField(upload_to='recettes'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(upload_to='restaurants'),
        ),
    ]
