# Generated by Django 3.0.7 on 2021-01-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegan', '0004_auto_20210103_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='picture',
            field=models.URLField(default='https://www.france-hotel-guide.com/fr/blog/wp-content/uploads/SOL-SEMILLA.jpg?ezimgfmt=ng:webp/ngcb5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(),
        ),
    ]
